sudo systemctl disable dhcpcd.service
sudo systemctl disable networking.service
sudo systemctl disable keyboard-setup.service
sudo systemctl disable avahi-daemon.service
sudo systemctl disable ssh.service
sudo systemctl disable bluetooth.service
sudo systemctl disable hostapd.service
sudo systemctl disable udhcpd.service
sudo systemctl disable hciuart